services:
    whastings.paidregistration.controler:
	    class: whastings\paidregistration\controller\main
	    arguments:
	        - '@config'
	        - '@controller.helper'
	        - '@template'
	        - '@user'
	whastings.paidregistration.listener:
		class whastings\paidregistration\controller\main_listener:
		tags:
			- { name: event.listener }