services:
        whastings.paidregistration.controler:
                class: whastings\paidregistration\controller\main
                arguments:
                        - '@config'
                        - '@controller.helper'
                        - '@template'
                        - '@user'
